### ISSUE TITLE
[BUG] Crash on startup.

### ISSUE THREAD

**Issue by Evan816** [TopazTK/KH-ReFined#80]
**Re:Fixed Version:**
3.0

**Game in Question:**
KH1, KH2, BBS

**Bug Description:**
After updating from 2.9 to 3.0, it crashes on startup. Had to fallback to 2.9 to play any of the games again.

I am playing on an SSD, i dont know if that affects anything.

**Comment by TopazTK** [comment]
Not enough information. May you post the log file for me to see?
It should be "ReFİned-DD-MM-YYYY.txt" in the game dir.

**Comment by Evan816** [comment]
[ReFined-26-08-2022.txt](https://github.com/TopazTK/KH-ReFined/files/9436798/ReFined-26-08-2022.txt)

here is my log file. even though it says launched with no errors i still get crashes :/

**Comment by TopazTK** [comment]
> [ReFined-26-08-2022.txt](https://github.com/TopazTK/KH-ReFined/files/9436798/ReFined-26-08-2022.txt)
> 
> here is my log file. even though it says launched with no errors i still get crashes :/

Something else is amiss. Can you get to the Discord Server?

**Comment by Evan816** [comment]
Yes I am able to. I'm already in the OpenKH server and my name is Evann#5440

**Comment by TopazTK** [comment]
The issue has been resolved. For those who are having the same issue, try running the game as an Admin.

**Comment by kwando1313** [comment]
Hey @TopazTK!

I know that this issue has been closed, but I'm facing a similar to the above. I tried running Re:Fix as admin, but that also still crashed, so I'm not really sure what to do here.

For further details, I'm trying to run this as part of rando, with the Panacea setup.

Thanks in advance!
